accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name ='logout'),
    

]

balance/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
    path('accounts/', include('accounts.urls')),
]

questions/urls.py
from django.urls import path
from questions import views


app_name = 'questions'

urlpatterns=[
    path('', views.index, name='index'),
    path('question/random/', views.random_question, name='random_question'),
    path('question/<int:id>/', views.question, name='question_show'),
    path('<int:id>/answer/<int:answer_id>/', views.answer_question, name='answer_question'),
    path('statistics/<int:id>/', views.answer_statistics, name='answer_statistics'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

questions/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length=100)
    question_a = models.TextField()
    question_b = models.TextField()

class UserAnswer(models.Model):
    ANSWER_CHOICES = [
        (0, '0'),
        (1, '1'),
    ]
    answer = models.PositiveSmallIntegerField(choices=ANSWER_CHOICES)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CustomUserCreationForm(UserCreationForm):

    # 원래 UserCreationForm 의 클래스에는 Meta 클래스가 원래의 User를 사용하고 있음.
    # 우리가 새로 만든 User로 바꿔줘야함. 
    class Meta:
        model = User
        fields = ('username', )

class CustomAuthenticationForm(AuthenticationForm):
    pass

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('questions:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save() 
            auth_login(request, user)
            return redirect('accounts:login')


    else: 
        form = CustomUserCreationForm()
    
    context = {
        'form': form,
    }

    return render(request, 'account_form.html', context) 
 
def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        
        if form.is_valid():
            auth_login(request, form.get_user())
          

    


            return redirect('questions:index')
  

    else:
        form = CustomAuthenticationForm()

    context ={
        'form': form,

    }
    return render(request, 'account_form.html', context)

def logout(request):
    auth_logout(request)
    return redirect ('accounts:login')

questions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, UserAnswer
import random
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, 'index.html')

@login_required
def question(request,id):
    twoquestion = get_object_or_404(Question, id=id)

    context = {
        'twoquestion': twoquestion
    }

    return render(request, 'answer_question.html', context)

@login_required
def random_question(request):
    total_questions = Question.objects.count()
    if total_questions == 0:
        # Handle case with no questions in the database
        return redirect('questions:index')  # Or some other appropriate action

    random_id = random.randint(1, total_questions)
    return redirect('questions:question_show', id=random_id)


def answer_question(request,id, answer_id):
    if request.method == "POST":
        answer = answer_id
        question = Question.objects.get(id=id)
        user = request.user
        if answer in [0, 1]:
            UserAnswer.objects.create(answer=answer, question=question, user=user)
            return redirect('questions:answer_statistics', id=question.id)  # Redirect to some success page or the same page
        else:
            # Handle the error. Maybe display a message to the user.
            twoquestion = question
        context={
            'twoquestion': twoquestion,
        }
 

    return render(request, 'answer_question.html', context)



def answer_statistics(request, id):
    total_answers = UserAnswer.objects.filter(question_id=id).count()
    questions = Question.objects.get(id=id)

    if total_answers == 0:
        context = {
            'questions': questions,
            'total_answers': total_answers,
            'count_0': count_0,
            'count_1': count_1,
            'percentage_0': 0,
            'percentage_1': 0
        }
    else:
        count_0 = UserAnswer.objects.filter(question_id=id, answer=0).count()
        count_1 = UserAnswer.objects.filter(question_id=id, answer=1).count()

        percentage_0 = int((count_0 / total_answers) * 100)
        percentage_1 = int((count_1 / total_answers) * 100)

        context = {
            'questions': questions,
            'count_0': count_0,
            'count_1': count_1,
            'total_answers': total_answers,
            'percentage_0': percentage_0,
            'percentage_1': percentage_1
        }

    return render(request, 'statistics.html', context)

accounts/templates/account_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>
{% else %}
    <h1>로그인</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class ="btn btn-primary">


</form>
{% endblock %}

questions/templates/answer_question.html
{% extends 'base.html' %}
{% block body %}

<div style="background-color: #383838; width:1300px; height: 1000px">
    <div class="container text-center">
        <div class="row">
            <div class="col p-3 mb-2 text-white">
                {{twoquestion.title}}
            </div>
        </div>
    </div>

    <div class="container text-center">
        <div class="row">
            <div class="col p-3 mb-2 text-white">
                {{twoquestion.question_a}} VS {{twoquestion.question_b}}
            </div>
        </div>
    </div>



    <div class="container text-center">
        <div class="row">
        <div id="s_left" class="col p-3 mb-2 text-white" style="height: 600px; width: 100px; border:1px solid rgb(255, 255, 255);">
            <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=0 %}" method="POST">
                {% csrf_token %}
                <button type="text" style="width: 600px; height: 585px; color: rgb(255, 255, 255); background-color: #383838;">
                    {{twoquestion.question_a}}
                </button>
        </div>
        <div id="s_right" class="col p-3 mb-2 text-white" style="height: 600px; width: 100px; border:1px solid rgb(255, 255, 255);">
            <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=1%}" method="POST">
                {% csrf_token %}
                <button type="text" style="width: 600px; height: 585px; color: rgb(255, 255, 255); background-color: #383838;">
                    {{twoquestion.question_b}}
                </button>


            </form>
        </div>
        </div>
    </div>    
</div>










{% endblock %}

questions/templates/index.html
{% extends 'base.html' %}
{% block body %}
    {% if user.is_authenticated %}
        <a href="{% url 'questions:random_question' %}" class="btn btn-primary btn-sm">게임시작</a>
        
    {% endif %}
{% endblock %}

questions/templates/question_show.html
{% extends 'base.html' %}
{% block body %}

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{twoquestion.title}}</h5>
      <p class="card-text">{{twoquestion.question_a}} VS {{twoquestion.question_b}} </p>
    </div>
    <ul class="list-group list-group-flush">
        <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=0 %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{{twoquestion.question_a}}">
      <li class="list-group-item">{{twoquestion.question_a}}</li>
        <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=1%}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{{twoquestion.question_b}}">
        </form>
      <li class="list-group-item">{{twoquestion.question_b}}</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
</div>

    <p>{{twoquestion.title}}</p>
    <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=0 %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="{{twoquestion.question_a}}">
    </form>
    <form action="{% url 'questions:answer_question' id=twoquestion.id answer_id=1%}" method="POST">
        {% csrf_token %}
        <input type="submit" value="{{twoquestion.question_b}}">
    </form>

  
    

{% endblock %}

questions/templates/statistics.html
{% extends 'base.html' %}
{% block body %}


<div class="container text-center">
    <div class="row">
        <div class="col p-3 mb-2 bg-secondary text-white">
            <p>다른 사람들은 무엇을 뽑았을까요</p>
        </div>
    </div>
</div>



<div class="container text-center">
    <div class="row">
      <div id="s_left" class="col p-3 mb-2 bg-dark text-white" style="height: auto; width: 100%; border:1px solid rgb(255, 255, 255);">
        <p> {{questions.question_a}} </p>
        <p>{{ percentage_0 }} %</p>
        <p>{{total_answers}}명 중 {{count_0 }}명 </p>
      </div>
      <div id="s_right"class="col p-3 mb-2 bg-dark text-white" style="height: auto; width: 100%; border:1px solid rgb(255, 255, 255);">
        
        <p>{{questions.question_b}}  </p>
        <p>{{ percentage_1 }} %</p>
        <p>{{total_answers}}명 중 {{count_1}}명 </p>
      </div>
    </div>
</div>    

<div class="container text-center">
    <a href="{% url 'questions:random_question' %}" class="btn btn-primary btn-sm">다음문제</a>
</div>

    
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <link rel="stylesheet" type="text/css" href="/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="/css/play.css">
    <meta charset="UTF-8">
    <title>밸런스 게임</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'questions:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{%url 'accounts:logout' %}">logout</a>
                    <a class="nav-link disabled">{{user}}</a>
                {% else %}
                    <a class="nav-link" href="{%url 'accounts:signup' %}">Signup</a>
                    <a class="nav-link" href="{%url 'accounts:login' %}">login</a>
                {% endif %}
              
            </div>
          </div>
        </div>
    </nav>
    
        
        {% block body %}
        {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>